#
# Alertik: a tiny 'syslog' server & notification tool for Mikrotik routers.
# This is free and unencumbered software released into the public domain.
#

name: CI

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  TRAVIS: 1

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    name: Build for ARMv6 and ARMv7
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download & extract GCC v11.2/musl (b76f37f) for armv6
      run:  toolchain/toolchain.sh "download_musl_armv6"
    - name: Download & build BearSSL for armv6
      run:  toolchain/toolchain.sh "download_build_bearssl"
    - name: Download & build libcurl for armv6
      run:  toolchain/toolchain.sh "download_build_libcurl"
    - name: Build Alertik for armv6
      run:  toolchain/toolchain.sh "do_build_armv6"
