#
# Alertik: a tiny 'syslog' server & notification tool for Mikrotik routers.
# This is free and unencumbered software released into the public domain.
#

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    name: Build for ARMv6 (compatible with v7 and Aarch64), and push to Dockerhub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download & extract GCC v11.2/musl (b76f37f) for armv6
      run:  toolchain/toolchain.sh "download_musl_armv6"
    - name: Download & build BearSSL for armv6
      run:  toolchain/toolchain.sh "download_build_bearssl"
    - name: Download & build libcurl for armv6
      run:  toolchain/toolchain.sh "download_build_libcurl"
    - name: Build Alertik for armv6
      run:  toolchain/toolchain.sh "build_alertik_armv6"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image for armv6/v7 and aarch64
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        platforms: linux/arm/v6, linux/arm/v7, linux/arm64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/alertik:latest
